
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry YouTubbeLinkInput_Textbox;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView Description_TextBox;

	private global::Gtk.Image Video_Image;

	private global::Gtk.Label VideoTitle_LBL;

	private global::Gtk.Label DownloadProgressLBL;

	private global::Gtk.Button Download_Audio_btn;

	private global::Gtk.Button Download_BTN;

	private global::Gtk.Button Retrive_Vid_Info;

	private global::Gtk.Button Exit_BTN;

	private global::Gtk.Label GtkLabel4;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.WidthRequest = 800;
		this.frame1.HeightRequest = 650;
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.YouTubbeLinkInput_Textbox = new global::Gtk.Entry();
		this.YouTubbeLinkInput_Textbox.WidthRequest = 580;
		this.YouTubbeLinkInput_Textbox.CanFocus = true;
		this.YouTubbeLinkInput_Textbox.Name = "YouTubbeLinkInput_Textbox";
		this.YouTubbeLinkInput_Textbox.IsEditable = true;
		this.YouTubbeLinkInput_Textbox.InvisibleChar = '•';
		this.fixed1.Add(this.YouTubbeLinkInput_Textbox);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.YouTubbeLinkInput_Textbox]));
		w1.X = 8;
		w1.Y = 26;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Youtube Url:");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w2.X = 14;
		w2.Y = 6;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.Description_TextBox = new global::Gtk.TextView();
		this.Description_TextBox.Buffer.Text = global::Mono.Unix.Catalog.GetString("Description");
		this.Description_TextBox.WidthRequest = 600;
		this.Description_TextBox.HeightRequest = 200;
		this.Description_TextBox.CanFocus = true;
		this.Description_TextBox.Name = "Description_TextBox";
		this.Description_TextBox.Editable = false;
		this.GtkScrolledWindow.Add(this.Description_TextBox);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w4.X = 10;
		w4.Y = 358;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Video_Image = new global::Gtk.Image();
		this.Video_Image.WidthRequest = 700;
		this.Video_Image.HeightRequest = 250;
		this.Video_Image.Name = "Video_Image";
		this.Video_Image.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Youtuube_Downloader.Screenshot from 2021-06-21 19-25-26.png");
		this.fixed1.Add(this.Video_Image);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Video_Image]));
		w5.X = 16;
		w5.Y = 75;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.VideoTitle_LBL = new global::Gtk.Label();
		this.VideoTitle_LBL.Name = "VideoTitle_LBL";
		this.VideoTitle_LBL.LabelProp = global::Mono.Unix.Catalog.GetString("Title");
		this.fixed1.Add(this.VideoTitle_LBL);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.VideoTitle_LBL]));
		w6.X = 14;
		w6.Y = 329;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.DownloadProgressLBL = new global::Gtk.Label();
		this.DownloadProgressLBL.Name = "DownloadProgressLBL";
		this.DownloadProgressLBL.LabelProp = global::Mono.Unix.Catalog.GetString("Not Downloading");
		this.fixed1.Add(this.DownloadProgressLBL);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.DownloadProgressLBL]));
		w7.X = 8;
		w7.Y = 577;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Download_Audio_btn = new global::Gtk.Button();
		this.Download_Audio_btn.WidthRequest = 150;
		this.Download_Audio_btn.CanFocus = true;
		this.Download_Audio_btn.Name = "Download_Audio_btn";
		this.Download_Audio_btn.UseUnderline = true;
		this.Download_Audio_btn.Label = global::Mono.Unix.Catalog.GetString("DownLoad Audio");
		this.fixed1.Add(this.Download_Audio_btn);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Download_Audio_btn]));
		w8.X = 626;
		w8.Y = 397;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Download_BTN = new global::Gtk.Button();
		this.Download_BTN.WidthRequest = 150;
		this.Download_BTN.CanFocus = true;
		this.Download_BTN.Name = "Download_BTN";
		this.Download_BTN.UseUnderline = true;
		this.Download_BTN.Label = global::Mono.Unix.Catalog.GetString("Download Video");
		this.fixed1.Add(this.Download_BTN);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Download_BTN]));
		w9.X = 627;
		w9.Y = 356;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Retrive_Vid_Info = new global::Gtk.Button();
		this.Retrive_Vid_Info.WidthRequest = 150;
		this.Retrive_Vid_Info.CanFocus = true;
		this.Retrive_Vid_Info.Name = "Retrive_Vid_Info";
		this.Retrive_Vid_Info.UseUnderline = true;
		this.Retrive_Vid_Info.Label = global::Mono.Unix.Catalog.GetString("Retrive VidInfo");
		this.fixed1.Add(this.Retrive_Vid_Info);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Retrive_Vid_Info]));
		w10.X = 617;
		w10.Y = 25;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Exit_BTN = new global::Gtk.Button();
		this.Exit_BTN.WidthRequest = 100;
		this.Exit_BTN.CanFocus = true;
		this.Exit_BTN.Name = "Exit_BTN";
		this.Exit_BTN.UseUnderline = true;
		this.Exit_BTN.Label = global::Mono.Unix.Catalog.GetString("Exit");
		this.fixed1.Add(this.Exit_BTN);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Exit_BTN]));
		w11.X = 669;
		w11.Y = 578;
		this.GtkAlignment.Add(this.fixed1);
		this.frame1.Add(this.GtkAlignment);
		this.GtkLabel4 = new global::Gtk.Label();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Youtube Downloader</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel4;
		this.Add(this.frame1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 800;
		this.DefaultHeight = 900;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Download_BTN.Pressed += new global::System.EventHandler(this.OnDownloadBTNPressed);
		this.Retrive_Vid_Info.Pressed += new global::System.EventHandler(this.OnRetriveVidInfoPressed);
		this.Exit_BTN.Pressed += new global::System.EventHandler(this.OnButton1Pressed);
	}
}
